services:
    semaphore:
        ports:
            - ${PORT:-8843}:3000
        image: semaphoreui/semaphore:${SEMAPHORE_IMAGE_TAG:-latest}
        environment:
            SEMAPHORE_DB_DIALECT: ${SEMAPHORE_DB_DIALECT:-mysql}
            SEMAPHORE_DB_HOST: ${SEMAPHORE_DB_HOST:-localhost}
            SEMAPHORE_DB_NAME: ${SEMAPHORE_DB_NAME:-semaphore}
            SEMAPHORE_DB_USER: ${SEMAPHORE_DB_USER:-root}
            SEMAPHORE_ADMIN: ${SEMAPHORE_ADMIN:-admin}
            SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD:-changeme}
            SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_ADMIN_NAME:-Admin}
            SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL:-admin@localhost}
